### ISSUE TITLE
I can't seem to select multiple segments in the storyboard

### ISSUE THREAD

**Issue by Sweeper777** [yonat/MultiSelectSegmentedControl#11]
I dragged a `UISegmentedControl` to the storyboard and set its class. I tried to select multiple segmented but no matter how hard I try, only one segment is selected. Is it impossible to get the storyboard to show multiple segments being selected?

**Comment by yonat** [comment]
I'm afraid that's not possible, since an `NSIndexSet` cannot be `IBInspectable`.
