### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by raysarebest** [yonat/MultiSelectSegmentedControl#15]
Currently, this project doesn't export any shared framework schemes in its `.xcodeproj`, so it cannot support Carthage. It would be nice to have Carthage support so I don't have to switch to CocoaPods or manual integration just for this library

**Comment by raysarebest** [comment]
Thanks for merging my PR! This issue can now be closed after adding tags similar to the ones already there to signify a release. Those are what Carthage looks for when downloading the latest version

**Comment by yonat** [comment]
Done, thanks for your guidance!
