### ISSUE TITLE
"No such module" when using CocoaPods with static frameworks

### ISSUE THREAD

**Issue by andriichernenko** [yonat/MultiSelectSegmentedControl#19]
I am working on a Swift project which uses CocoaPods 1.5.3 with static frameworks. 

It doesn't seem possible to import `MultiSelectSegmentedControl` in Swift code. The build fails with the "No such module 'MultiSelectSegmentedControl'" error.

[This SO issue](https://stackoverflow.com/a/44640294/1318939) might explain why, but unfortunately I don't have the opportunity to test the proposed solution.

**Comment by yonat** [comment]
When you get an opportunity to try it, I;d love to hear how it went.
