### ISSUE TITLE
not working anymore in iOS 13 beta 5

### ISSUE THREAD

**Issue by JotWee** [yonat/MultiSelectSegmentedControl#22]
**Description of the problem😘*
crash, because `self.subviews` changed

**Comment by yonat** [comment]
I pushed a fix for the crash, but it's only a partial fix:
On iOS 13 it shows only a single segment selected.

To fix multiple selection on iOS 13 will require more work, I'll fix it if/when I find the time.

**Comment by yonat** [comment]
@JotWee I ended up re-writing the whole thing to support multiple selection in iOS 13 - see version 2.0.0.
