### ISSUE TITLE
v2.0

### ISSUE THREAD

**Issue by JotWee** [yonat/MultiSelectSegmentedControl#23]
Am a bit lost with the new version:
- example not working
- how to use w/o CocoaPods?
- where to find SweeterSwift?

Maybe this is just an issue of a lack of knowledge on my side, but I have absolutely no idea how to get this to work in my project

**Comment by yonat** [comment]
Hi @JotWee do you copy the files manually?
If so, you'll need to copy the dependency from https://github.com/yonat/SweeterSwift .

But I recommend you use either [CocoaPods](https://cocoapods.org) or the [Swift Package Manager](https://swift.org/package-manager/).
