### ISSUE TITLE
MultiSelectSegmentedControl not recognized class in interface builder since upgrade

### ISSUE THREAD

**Issue by StainlessStlRat** [yonat/MultiSelectSegmentedControl#24]
Hello, I just recently ran a pod update from 1.2.1 to 2.0.1. For whatever reason, Interface Builder is not recognizing the class anymore. It refuses to be set. So while the project compiles (after updating headers to -Swift.h, updating a couple of API calls), interface builder falls back to creating a UISegmentedControl and then the properties (like selected indexes) fail as unrecognized selectors.

iOS 13 release is right around the corner. Any help? Something I'm doing wrong in the transition from obj C to swift?

**Comment by yonat** [comment]
Instead of adding a `UISegmentedControl` and changing its class, you'll need to add a regular `UIView` and then set its class to `MultiSelectSegmentedControl`.

**Comment by StainlessStlRat** [comment]
Thanks! When I tried that I lost the ability to set it up with indexes and titles and such. Is there a reason that broke? Is it easily fixable?

**Comment by yonat** [comment]
Yes, the new version no longer inherits from `UISegmentedControl` because iOS 13 makes it impossible to have multi selection with the built-in control.

I'm afraid there's no way to set the titles in IB for the new version, you'll have to do it in code.

**Comment by StainlessStlRat** [comment]
Oh man that's so lame of them! Is there no way to make IBInspectable values so we can set It up in IB again?

**Comment by yonat** [comment]
Arrays can't be IBInspectable, only values. :-(
