### ISSUE TITLE
Text oversized; Does not appear the same as before. How do we control it?

### ISSUE THREAD

**Issue by StainlessStlRat** [yonat/MultiSelectSegmentedControl#25]
Old Behavior
![IMG_7125](https://user-images.githubusercontent.com/16851186/64822355-aa7b4b00-d569-11e9-827f-82a0b8ed4c4c.PNG)

New Behavior
![IMG_7126](https://user-images.githubusercontent.com/16851186/64822356-abac7800-d569-11e9-835a-ea65c764cdfa.PNG)

Would be good to have as close to original behavior as possible to avoid UI breaks/contractions

**Comment by yonat** [comment]
I changed the font and spacing to better mimic the old appearance, hope it works better for you now.

**Comment by StainlessStlRat** [comment]
Thank you I will try now and let you know!

**Comment by StainlessStlRat** [comment]
It looks good! Thank you Yonat!
