### ISSUE TITLE
Ability to set selected segment's label's text color

### ISSUE THREAD

**Issue by StainlessStlRat** [yonat/MultiSelectSegmentedControl#26]
When the segment is selected, it sets the label color to .background.

This is fine for the default colors, but my tint is a shade of blue. I'd prefer that when the segment is selected, the text color is white, but in night mode the text will be black.

**Comment by yonat** [comment]
I made two changes that should help:
1. use the real background color of the view behind instead of the system background.
2. implement `setTitleTextAttributes(_:for:)` (works like its `UISegmentedControl` counterpart).

Hope it works for you!

**Comment by StainlessStlRat** [comment]
Perfect! Thanks for being so responsive!

**Comment by StainlessStlRat** [comment]
Not sure what I'm doing wrong here, but I get an unrecognized selector error in obj C (even though the function autofills). _ownedComponents is the multiselectedsegmentedcontrol:

NSDictionary *attributes = @{NSForegroundColorAttributeName : [UIColor whiteColor]};
[_ownedComponents setTitleTextAttributes:attributes for:UIControlStateSelected];

**Comment by yonat** [comment]
About the undefined selector:
I think the objc counterpart is `setTitleTextAttributes:forState` (instead of the `for:` in Swift) - like in https://developer.apple.com/documentation/uikit/uisegmentedcontrol/1618570-settitletextattributes?language=objc .

**Comment by StainlessStlRat** [comment]
It won't compile if I set it to that. Says "no recognized selector"

**Comment by yonat** [comment]
About the background color behavior:
What do you see when you select a segment?
Would you upload a picture? (with some background around the control for comparison)

**Comment by yonat** [comment]
Do you get auto completion for the objc?

**Comment by StainlessStlRat** [comment]
Yes it autocompleted weirdly enough!

**Comment by StainlessStlRat** [comment]
<img width="545" alt="Screen Shot 2019-09-20 at 12 49 21 AM" src="https://user-images.githubusercontent.com/16851186/65309267-97a3e000-db40-11e9-87bb-230a67ec90d7.png">

**Comment by StainlessStlRat** [comment]
I want the same colors whether or not it's night mode if that matters

**Comment by StainlessStlRat** [comment]
Also anyway to make the divider thinner? Feels like it's thicker than it used to be

**Comment by yonat** [comment]
Where does the  white comes from? The unselected background is clear.
If you make the  white view into the superview of the control, it should work.

**Comment by StainlessStlRat** [comment]
I've got it set to white in interface builder. If I set it to clear won't the background be dark? That'll clash with the blue color/make it hard to read

**Comment by yonat** [comment]
dividers are the  same width as border, so:

```swift
multi.borderWidth = 0.5
```

**Comment by StainlessStlRat** [comment]
Ah I looked in the code and could swear it was set to 1.0

**Comment by yonat** [comment]
Hmmm. didn't thing to use the control's own `backgroundColor`. That's a good idea actually.

**Comment by StainlessStlRat** [comment]
@IBInspectable open dynamic var borderWidth: CGFloat = 1 { 

Does this mean it's set to 1.0?

**Comment by yonat** [comment]
Yes.

**Comment by StainlessStlRat** [comment]
Ohhh gotcha

**Comment by StainlessStlRat** [comment]
Small defects if I set it lower. Look at the left hand side. You can see white around the border
<img width="157" alt="Screen Shot 2019-09-20 at 12 57 40 AM" src="https://user-images.githubusercontent.com/16851186/65309836-c1113b80-db41-11e9-8f5c-1fb1785ca40a.png">

**Comment by StainlessStlRat** [comment]
Awesome! Thanks for being so responsive!

**Comment by yonat** [comment]
You caught me in a good time!
Just pushed 2.1.1 with the fixes. Now your code should just work, without setting foreground color.

**Comment by StainlessStlRat** [comment]
Hm still getting the same behavior

**Comment by StainlessStlRat** [comment]
Did you fix the sliver showing on the left? I still see that too. Maybe I messed something up

**Comment by yonat** [comment]
Weird. Sure you updated the pod/package? Maybe do a Product>Clean and then try again.

**Comment by StainlessStlRat** [comment]
Clean rebuild fixed it!

**Comment by StainlessStlRat** [comment]
<img width="545" alt="Screen Shot 2019-09-20 at 1 19 03 AM" src="https://user-images.githubusercontent.com/16851186/65311169-ab514580-db44-11e9-921d-80a7bdb54bf2.png">

**Comment by StainlessStlRat** [comment]
There's still an ever so small sliver of white on the leftmost segment if it's selected. Any idea what that is? I'm just worried that on other devices it might be even more pronounced!

**Comment by yonat** [comment]
Probably antialiasing. Doesn't reproduce for me, maybe try to ensure the view is aligned to whole pixels and see if it changes anything.

**Comment by StainlessStlRat** [comment]
Ya it's definitely whole pixels. I didn't even realize you could set constraints that were sub pixel. Happens on another view where I use the tool that just uses autoresizemasks too

**Comment by StainlessStlRat** [comment]
When you test for the sliver of white on the side, have you set the border width to 0.5? It only happens when I try to make the border sizes look more like they used to by setting them to 0.5

**Comment by yonat** [comment]
Half pixel can happen unintentionally, as a result of centering or indenting.
Anyway, it doesn't reproduce for me so I can't fix it. If you send me a project that reproduce this behavior (and specify on which simulator to run it) then I can try to fix it.
