### ISSUE TITLE
Doesn't work in Interface Builder

### ISSUE THREAD

**Issue by MaxHaertwig** [yonat/MultiSelectSegmentedControl#27]
**Description of the problem:**
I created a new iOS project in Xcode 11 GM 2 and added the MultiSelectSegmentedControl dependency via SPM. I added a UIView in Interface Builder and set its class to MultiSelectSegmentedControl. Next to "Designables", it tries to compile, but fails with the errors in the image below. However, when compiling the app for running, the build succeeds.

It seems Interface Builder tries to compile MultiSelectSegmentedControl and all its dependencies for all platforms, including tvOS. Should I submit a pull request adding the missing #if os checks to SweeterSwift?

<img width="272" src="https://user-images.githubusercontent.com/9899051/65373787-5f0c1f80-dc82-11e9-8e6f-241e9d183ad7.png">

**Comment by yonat** [comment]
Pushed 1.0.5 with the fix, thanks for reporting!
