### ISSUE TITLE
Carthage support no shared framework schemes

### ISSUE THREAD

**Issue by PierreBrisorgueil** [yonat/MultiSelectSegmentedControl#34]
Hello, 

thx for your work ! 

I saw the issue and PR to add carthage however by my side on the latest version :

`github "yonat/MultiSelectSegmentedControl" ~> 2.3.0` || `github "yonat/MultiSelectSegmentedControl" "master"`

*** Skipped building MultiSelectSegmentedControl due to the error:
Dependency "MultiSelectSegmentedControl" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/yonat/MultiSelectSegmentedControl/issues/new

**Comment by yonat** [comment]
Sorry, I don't actually use Carthage so it's a bit of trouble me to check this.

But it would be very welcome if you submit a PR that adds Carthage support!
