### ISSUE TITLE
tint color interfering with title color set via attributes

### ISSUE THREAD

**Issue by trapper-** [yonat/MultiSelectSegmentedControl#36]
If I set the tintColor (to change the border and selected color) and also use the foregroundColor titleTextAttribute to set the title text color to something different then all looks fine initially.

Presenting or dismissing another VC causes the tintColorDidChange event to fire again which cascades down to the segments, then updateColors, and finally label.textColor = foregroundColor is called that overrides the button title attributes.

The result is the title color changing back to the correct color any time I change a segment selection, and then back to the wrong color if I present/dismiss any VC.

**Comment by yonat** [comment]
Thanks for reporting, fixed in 2.3.1.
