### ISSUE TITLE
Add multiline support

### ISSUE THREAD

**Issue by askiiRobotics** [yonat/MultiSelectSegmentedControl#37]
**Description:**
In MultiSelectSegment.swift
in UILabel init you can provide an additional attribute to set numberOfLines property to 0 in order to support multiline.

Thank you for your awesome project anyway!

**Comment by yonat** [comment]
Added `titleConfigurationHandler` in 2.3.2 for that:

```swift
multiSelect.titleConfigurationHandler = {
    $0.numberOfLines = 0
    $0.lineBreakMode = .byWordWrapping
}
```
You'll need to set some width constraints for this to have an effect.
