### ISSUE TITLE
Builds and runs, but can not archive using interface builder

### ISSUE THREAD

**Issue by RaaghavM** [yonat/MultiSelectSegmentedControl#41]
I am using this multi-select segmented control using Interface Builder and not SwiftUI, and everything runs smoothly. However, when I go to archive the project to publish in the App Store, it seems to give compiler errors in the MultiSegmentPicker.swift file, although this code should not run since I am not using SwiftUI. Is there a way to get around this issue?

<img width="866" alt="Screen Shot 2020-07-02 at 7 46 35 PM" src="https://user-images.githubusercontent.com/14805803/86417982-bec93980-bc9c-11ea-9f4a-f1067e5a112f.png">

**Comment by yonat** [comment]
Try using the `master` branch instead of the `swiftui` branch.

**Comment by RaaghavM** [comment]
Thanks for your quick response! I believe I'm using the `master` branch? I'm using Swift Package Manager and followed the instructions for setup in the `README` for this project. I am simply using the URL [https://github.com/yonat/SweeterSwift](https://github.com/yonat/SweeterSwift). Is there something else I'm missing?

**Comment by yonat** [comment]
What  do you see in the project settings > Swift Packages?

**Comment by yonat** [comment]
Sorry, I missed the  problem. Try using version 2.2.0 until I find a better fix, sorry.
(I'm assuming you can't change the deployment target to iOS 13...)

**Comment by yonat** [comment]
This seems to be a bug in spm: https://bugs.swift.org/browse/SR-11907

**Comment by RaaghavM** [comment]
I'm actually using iOS 13 as the deployment target, but this problem still persists. I'll try using version 2.2.0, or CocoaPods if that doesn't work either. Thanks for your help!

**Comment by RaaghavM** [comment]
Used CocoaPods and it was successful.
