### ISSUE TITLE
Setting the MultiSegmentPicker to be fully justified

### ISSUE THREAD

**Issue by avicooper1** [yonat/MultiSelectSegmentedControl#42]
**Description:**
I am trying to have the MultiSegmentPicker extend the width of the screen. Before I tried to implement this in SwiftUI, I was able to achieve this:

![IMG_76297A361A7F-1](https://user-images.githubusercontent.com/11204241/88002666-0ccda200-cad1-11ea-9514-ac80064e982d.jpeg)

by embedding the control inside a view, and then, after `viewDidAppear`, setting the frame of the control to the size of the view which it was inside.

I am now migrating my app to SwiftUI and trying to achieve similar behavior. I am not as knowledgable in it, and am having some difficulty. The code I am using is:
```
struct GradePickSegmentedControl: View {
    let items: [String]
    @Binding var indexSet: IndexSet
    var body: some View {
        MultiSegmentPicker(
            selectedSegmentIndexes: $indexSet,
            items: items
        )
        .background(Color.red)
        .fixedSize(horizontal: false, vertical: true)
    }
}
```
 which is producing:

![Simulator Screen Shot - iPhone 11 - 2020-07-20 at 21 34 52](https://user-images.githubusercontent.com/11204241/88002813-66ce6780-cad1-11ea-82f4-b311023d93bf.png)

From what I understand about SwiftUI, the parent view gives the available size to the child, but ultimately the child decides how large it will be. It thus seems that it is up to the control to expand each cell to take up the full width of the screen. But I am unsure how to do this. 

Any help would be appreciated.

**Comment by yonat** [comment]
Good question. I'm not able to fix that, it's not clear to me how theSwiftUI `frame` relates to the UIKit constraints. If you find a solution, please let me know!

**Comment by yonat** [comment]
Found the culprit! Fixed in version 2.3.4.

**Comment by avicooper1** [comment]
Thank you!

**Comment by abeiderman** [comment]
Hi, looks like this behavior stopped working in 2.3.5. With 2.3.4 I can get it to extend the full width of the parent with `.fixedSize(horizontal: false, vertical: true)` but if I upgrade to 2.3.5 it reverts to the behavior prior to 2.3.4.

**Comment by yonat** [comment]
What happens if you try without fixedSize?

**Comment by abeiderman** [comment]
With 2.3.5 I get the same result (aligns left and does not extend full width) with or without `fixedSize`.
