### ISSUE TITLE
Doesn't work in Interface Builder for Xcode 12.4

### ISSUE THREAD

**Issue by jamiedaniel** [yonat/MultiSelectSegmentedControl#44]
**Description of the problem:**
I have an existing project that uses MultiSelectSegmentedControl. Once I upgraded to Xcode 12.4 it stopped working in Interface Builder with the following errors:

![Screen Shot 2021-02-10 at 8 53 59 AM](https://user-images.githubusercontent.com/2378140/107518997-ad72d480-6b7d-11eb-9529-3ab7a27d796c.png)
![Screen Shot 2021-02-10 at 8 54 30 AM](https://user-images.githubusercontent.com/2378140/107518999-ae0b6b00-6b7d-11eb-93e2-1489dab45178.png)

**Minimal project that reproduces the problem (so I'll be able to figure out how to fix it):**
This happens in all applications in Xcode 12.4

**Comment by yonat** [comment]
Works fine for me... Can you link to a minimal project that reproduces the problem? (as describe in https://ootips.org/yonat/repex/)
