### ISSUE TITLE
Adjust Text Size

### ISSUE THREAD

**Issue by willm132** [yonat/MultiSelectSegmentedControl#47]
For `UISegmentedControl`'s you are able to use `.apportionsSegmentWidthsByContent = true`, this will automatically decrease the text size so everything fits in the `UISegmentedControl`'s width.

When using a `MultiSelectSegmentedControl` and using `.apportionsSegmentWidthsByContent = true` it will cut off elements since the test size is not decreasing to fit. 

Example of what it should do:
![Normal Segment](https://user-images.githubusercontent.com/47162632/118321700-f7948a80-b4cb-11eb-942f-676aa173c0a1.png)

What it currently does:
![MultiSegment](https://user-images.githubusercontent.com/47162632/118321723-fcf1d500-b4cb-11eb-8b81-f6c6453917b1.png)

**Comment by yonat** [comment]
This control never changes the text size - that's up to you.
What `apportionsSegmentWidthsByContent` does is make each segment width match its content size.

For example:
<img width="256" alt="Screen Shot 2021-05-15 at 15 26 39" src="https://user-images.githubusercontent.com/837421/118361065-5ae8f000-b592-11eb-8ac4-7beb38240386.png">

**Comment by willm132** [comment]
Is there anyway to adjust the text size so I can fit every element in the view?

**Comment by yonat** [comment]
The closest is `setTitleTextAttributes()` . It doesn't do the automatic scaling like `UILable.adjustsFontSizeToFitWidth` though.
