### ISSUE TITLE
No such module 'MultiSelectSegmentedControl'

### ISSUE THREAD

**Issue by willm132** [yonat/MultiSelectSegmentedControl#48]
I am getting error No such module 'MultiSelectSegmentedControl' when attempting to build for Mac Catalyst. 

I am using Cocoapods.

**Comment by yonat** [comment]
Works for me:

<img width="351" alt="Screen Shot 2021-08-21 at 6 10 37 PM" src="https://user-images.githubusercontent.com/837421/130326319-f2a5208b-453a-4370-bfd4-b6c8b3ed526e.png">

Please create a minimal project that reproduces this problem, create a github project with its code, and link to it here. (See https://ootips.org/yonat/repex/)

**Comment by willm132** [comment]
I updated via cocoapods and still getting this issue. All of my other pods are working fine.

**Comment by willm132** [comment]
Could not find module 'MultiSelectSegmentedControl' for target 'arm64-apple-ios-macabi'; found: x86_64-apple-ios-macabi, x86_64

**Comment by yonat** [comment]
To help, I need to be able to reproduce this problem.
Please create a minimal project that reproduces this problem - See https://ootips.org/yonat/repex/ for instructions.

**Comment by willm132** [comment]
It works when I create a minimal project but not in my current project.

**Comment by yonat** [comment]
This means that the problem is not in the library, but in the project.

One way to debug this is to add files to the minimal projects one by one, until the problem appears.

Another way is to remove files from your project until the problem disappears.

**Comment by willm132** [comment]
I have 30+ files with thousands of lines of code. Is there anyway to use Xcode to debug the issue?

**Comment by yonat** [comment]
Thousands of lines of code is a small project. The method I suggested would probably take no more than a couple of hours. Good luck!

**Comment by willm132** [comment]
I will just remove this and use something else. Thanks for the help!
