### ISSUE TITLE
Runtime error upon startup on iOS 14 devices when compiled with Xcode 13.3+

### ISSUE THREAD

**Issue by lukemmtt** [yonat/MultiSelectSegmentedControl#50]
**Description of the problem:**
This module has been very helpful for me and my project, but starting with Xcode 13.3, I began receiving many reports from iOS 14 users stating that my app had begun crashing immediately at startup, and this module has been identified as the culprit. More specifically, the issue is in the SweeterSwift dependency which this package relies on.

My colleague forked the SweeterSwift package to devise a workaround here: https://github.com/zabolotiny/SweeterSwift

Similarly, I can see another fork of this dependency has been created by another user ( @Janek-CL ) that claims to fix the issue in a different way: https://github.com/CONVELOP-GbR/SweeterSwift

(Issue cross-posted in the SweeterSwift module as https://github.com/yonat/SweeterSwift/issues/7 )

**Comment by yonat** [comment]
Thanks! I added tylerjames fix to SweeterSwift 1.2.1 .

**Comment by lukemmtt** [comment]
Is @Janek-CL the "tylerjames" you're referring to? Thanks for your work!

**Comment by 0xSkash** [comment]
@lukemmtt No, I used the "tylerjames" fix in my forked repo. :)

**Comment by Janek-CL** [comment]
@lukemmtt No, tylerjames found a fix for the problem. I used his solution in my forked repo.
