### ISSUE TITLE
Unsupported swift architecture using cocoa pods on M2 MacBook

### ISSUE THREAD

**Issue by StainlessStlRat** [yonat/MultiSelectSegmentedControl#51]
**Description of the problem:**
Project fails to compile due to:
"unsupported Swift architecture"

The pod works fine on my older MacBook, but fails to compile on my new M2 chipset.

<img width="1512" alt="Screenshot 2023-09-19 at 12 25 55 PM" src="https://github.com/yonat/MultiSelectSegmentedControl/assets/16851186/fa5947a6-10dd-44de-815d-3771e434a823">

**Comment by yonat** [comment]
Works fine in my own M2...
Maybe the problem is somewhere else?
Maybe clean + delete derived data?
