### ISSUE TITLE
selectedSegmentTitles should not be assign

### ISSUE THREAD

**Issue by stonemonk** [yonat/MultiSelectSegmentedControl#9]
The selectedSegmentTitles property is marked assign, but no assignment method exists to handle this which is mis-leading because the developer would reasonably think that its a valid way to change the selection.

Further XCode creates a warning because by having it marked assignment, it is creating an ivar implicitly which it recognizes is never used.

Therefore, the selectedSegmentTitles property should be marked readonly instead of assign.

**Comment by yonat** [comment]
You are absolutely right, thank you.

I just fixed it.
